name: release-grpc

on:
  push:
    tags:
      - 'grpc-v*' # Push events to matching grpc-v*, i.e. grpc-v1.0, grpc-v1.0.1

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-grpc-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-grpc-
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Set Release Tag Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./grpc
          file: ./grpc/Dockerfile.grpc
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKER_USER }}/grpc-debug:latest
            ${{ vars.DOCKER_USER }}/grpc-debug:${{ github.sha }}
            ${{ vars.DOCKER_USER }}/grpc-debug:${{ env.RELEASE_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
